name: Keep Render Service Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -f https://your-backend-url.onrender.com/ping || echo "Ping failed"
          curl -f https://your-backend-url.onrender.com/health || echo "Health check failed"
